### ISSUE TITLE
Creating a clan with exotic characters crashes during clan creation

### ISSUE THREAD

**Issue by stenno** [tnnt-devteam/tnnt#33]
After logging in, trying to create a clan with exotic characters will throw an 
OperationalError at /clanmgmt
(1267, "Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")
Reproduce by trying to create a clan called "👁️👄👁️👍"
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/160513/199210696-d65889a3-c9a0-4a0c-9b6d-7d8b4a92a231.png">

**Comment by entrez** [comment]
This is related to tnnt-devteam/python-backend#25 and any further discussion should go there (since this repo is for the actual NetHack variant).  The actual giant backtrace has been silenced now and there's a plainer "you can't use emoji" message instead, but we're going to revisit it some time after the tournament again to see about making emoji clan names actually work.  There are more details in that other issue.
