### ISSUE TITLE
Orcish Town isn't detected for achievements if it's a bones level

### ISSUE THREAD

**Issue by AndrioCelos** [tnnt-devteam/tnnt#34]
This issue is related to NetHack/NetHack#1144.

Orcish Town does not seem to be recognised if it's a bones level. That means the achievement 'No Rulez' is awarded immediately upon entering, and 'Minetown Avenger' is unavailable that game. Also, the wandering orcs don't appear on other levels.

It's possible that this also occurs with the Big Room.

**Comment by entrez** [comment]
Thanks, Andrio.  The No Rulez issue applies to more than just Orcish Town, since it's also true of any bones Minetown where the dead hero got No Rulez -- someone had reported that happening earlier.  But it's definitely going to be more common with Orcish Town bones.

And it's a good point how this issue applies to Minetown Avenger, too.  We'll have to figure out what to do about that.  I guess we'd probably have to make bones files preserve their slev->which_level values if we want people to be able to get Minetown Avenger from a bones file.

I don't think the bigroom would have this problem since the special level name (like "bigrm") is preserved when you get bones, it's just the level variant that is unidentifiable, and the clear the bigroom achievement doesn't use that info since it applies to all variants.  But not 100% sure.

**Comment by entrez** [comment]
This should be fixed by e7accbd.  Orcish town raiding parties not appearing isn't changed, because that's a vanilla behavior outside the scope of TNNT changes.
